[package]
name = "volt-letter-ensea"
version = "0.1.0"
entrypoint = "template-letter.typ"
authors = ["Dawod-G"]
license = "MIT"
description = "Unofficial Typst template for short documents at ENSEA, a French engineering school."
repository = "https://github.com/Dawod-G/ENSEA_Typst-Template"
keywords = ["ensea", "school", "engineering", "report"]
categories = ["report"]
exclude = ["thumbnail-letter.png"]

[template]
path = "template"
entrypoint = "main-letter.typ"
thumbnail = "thumbnail-letter.png"